language: generic
sudo: required
dist: trusty

cache:
  - apt

addons:
  apt:
    sources:
      - cassou-emacs
      - ubuntu-elisp
    packages:
      - emacs23-nox
      - emacs24-nox
      - emacs-snapshot
      - texinfo

env:
  matrix:
    - EMACS=emacs23           TARGET=check
    - EMACS=emacs24           TARGET=check
    - EMACS=emacs-snapshot    TARGET=check
    - TARGET=deploy-manual
  global:
    - secure: "ejv1+ub/v+Hm/23fhp4zLAHT3HiCG+YdDHai57LDe4LfEZCeGz4i/6LazbPbwm58v2YuKvMcdNshebc1s4A293ARJryPyFfW/8kEe+3hQ+cDxunNdHfqcS8SyhcDG0mrv7dqiVAtMJqB8qZb0c161KeEM8nyhC0wyQ+EZ5qJnzM="

matrix:
  allow_failures:
    - env:
        - EMACS=emacs-snapshot    TARGET=check

install:

script:
  - makeinfo --version
  - make $TARGET

notifications:
  email: false
  irc: "irc.freenode.org#haskell-emacs"

# Local Variables:
# indent-tabs-mode: nil
# coding: utf-8
# End:
