language: emacs-lisp

env:
  global:
    - PATH=$HOME/.cask/bin:$HOME/.evm/bin:$PATH
  matrix:
    #   # Cask does not support emacs < 24
    # - EVM_EMACS=emacs-23.4-bin
    #   # dependencies break in ghc-core.el about cl-lib
    # - EVM_EMACS=emacs-24.1-bin
    #   # dependencies break in ghc-core.el about cl-lib
    # - EVM_EMACS=emacs-24.2-bin
    - EVM_EMACS=emacs-24.3-bin
    - EVM_EMACS=emacs-24.4-bin
  # allow_failures:
  #   - EVM_EMACS=emacs-23.4-bin
  #   - EVM_EMACS=emacs-24.1-bin
  #   - EVM_EMACS=emacs-24.2-bin

before_install:
  - curl -fsSkL https://gist.github.com/rejeep/7736123/raw > travis.sh && source ./travis.sh
  # install the matrix's emacs version
  - evm install $EVM_EMACS --use --skip
  # install deps for cask
  - cask

script:
  lsb_release -a && emacs --version && make check

notifications:
  email: false

# Local Variables:
# indent-tabs-mode: nil
# coding: utf-8
# End:
