language: generic
sudo: required

services:
  - docker

env:
  matrix:
    - TARGET=emacs24
    - TARGET=emacs-snapshot
    - TARGET=doc

install: |
    case "$TARGET" in
      emacs24)
        docker build -t haskell-interactive-mode:24 ./emacs-24;
        ;;
      emacs-snapshot)
        docker build -t haskell-interactive-mode:snapshot ./emacs-snapshot;
        ;;
      doc)
        sudo apt-get update &&
        sudo apt-get install -y python-pip &&
        sudo pip install sphinx;
        ;;
      *)
    esac

script: |
    case "$TARGET" in
      emacs24)
        docker run -it haskell-interactive-mode:24;
        ;;
      emacs-snapshot)
        docker run -it haskell-interactive-mode:snapshot;
        ;;
      doc)
        make doc;
        ;;
      *)
    esac


notifications:
  email: false
  irc: "irc.freenode.org#haskell-emacs"

# Local Variables:
# indent-tabs-mode: nil
# coding: utf-8
# End: