language: generic
sudo: required
dist: trusty

env:
  matrix:
    - TARGET=emacs24
    - TARGET=emacs-snapshot
    - TARGET=doc

install: |
    case "$TARGET" in
      emacs24)
        sudo apt-get update &&
        sudo apt-get install --no-install-suggests --no-install-recommends --force-yes emacs24-nox &&
        sudo apt-get install -y ghc;
        ;;
      emacs-snapshot)
        sudo add-apt-repository -y ppa:ubuntu-elisp/ppa &&
        sudo apt-get update &&
        sudo apt-get install --no-install-suggests --no-install-recommends --force-yes emacs-snapshot &&
        sudo apt-get install -y ghc;
        ;;
      doc)
        sudo apt-get update &&
        sudo apt-get install -y python-pip &&
        sudo pip install sphinx;
        ;;
      *)
    esac

script: |
    case "$TARGET" in
      emacs24)
        EMACS=emacs24 make check;
        ;;
      emacs-snapshot)
        EMACS=emacs-snapshot make check;
        ;;
      doc)
        make doc;
        ;;
      *)
    esac


notifications:
  email: false
  irc: "irc.freenode.org#haskell-emacs"

# Local Variables:
# indent-tabs-mode: nil
# coding: utf-8
# End: