# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

clone_depth: 1

init:

install:
  - choco install emacs
  - choco install ghc
  - choco install cabal
  - choco install haskell-stack
  - refreshenv

build_script:
  - C:\msys64\usr\bin\bash -l -c "cd ${APPVEYOR_BUILD_FOLDER} && make check"

test_script:
